name: 'Install powershell'
runs:
  using: "composite"
  steps:
    - run: chmod +x ${{ github.action_path }}/install.sh
      shell: bash
    - run: ${{ github.action_path }}/install.sh
      shell: bash
      